-- @Autor:                  Barcenas Avelar Jorge Octavio - 
--                          Abraham Josué Lazaro Martínez
-- @Fecha creación:         2/01/2022
-- @Descripción:            Creacion de indices

connect sys/system as sysdba 

-- MODULO: CLIENTE

-- 
-- TABLE: PLAN_SUBSCRIPCION_HISTORICO 
--

CREATE INDEX CLIENTE.PSH_PLAN_SUBSCRIPCION_ID_IX
ON  CLIENTE.PLAN_SUBSCRIPCION_HISTORICO(PLAN_SUBSCRIPCION_ID)
TABLESPACE CLIENTE_IX_TBS;

-- 
-- TABLE: PLAN_SUBSCRIPCION
--

CREATE UNIQUE INDEX CLIENTE.PS_CLAVE_UK
ON  CLIENTE.PLAN_SUBSCRIPCION(CLAVE)
TABLESPACE CLIENTE_IX_TBS;

-- 
-- TABLE: TARJETA_CREDITO 
--

CREATE UNIQUE INDEX CLIENTE.TC_USUARIO_ID_UK
ON  CLIENTE.TARJETA_CREDITO(USUARIO_ID)
TABLESPACE CLIENTE_IX_TBS ;

-- 
-- TABLE: CARGO_MENSUAL 
--

CREATE INDEX CLIENTE.CARGO_MENSUAL_TARJETA_CREDITO_ID_IX
ON  CLIENTE.CARGO_MENSUAL(TARJETA_CREDITO_ID)
TABLESPACE CLIENTE_IX_TBS;

CREATE UNIQUE INDEX CLIENTE.CARGO_MENSUAL_FOLIO_UK 
ON  CLIENTE.CARGO_MENSUAL(FOLIO)
TABLESPACE CLIENTE_IX_TBS;

-- 
-- TABLE: USUARIO 
--

CREATE UNIQUE INDEX CLIENTE.USUARIO_USERNAME_UK
ON  CLIENTE.USUARIO(USERNAME)
TABLESPACE CLIENTE_IX_TBS;

CREATE UNIQUE INDEX CLIENTE.USUARIO_EMAIL_UK
ON  CLIENTE.USUARIO(EMAIL)
TABLESPACE CLIENTE_IX_TBS;

CREATE UNIQUE INDEX CLIENTE.USUARIO_RFC_UK
ON  CLIENTE.USUARIO(RFC)
TABLESPACE CLIENTE_IX_TBS;

CREATE INDEX CLIENTE.USUARIO_DUENIO_CUENTA_ID_IX
ON  CLIENTE.USUARIO(USUARIO_DUENIO_CUENTA_ID)
TABLESPACE CLIENTE_IX_TBS;

CREATE INDEX CLIENTE.USUARIO_PLAN_SUBSCRIPCION_ID_IX
ON  CLIENTE.USUARIO(PLAN_SUBSCRIPCION_ID)
TABLESPACE CLIENTE_IX_TBS;

-- 
-- TABLE: DISPOSITIVO 
--
CREATE INDEX CLIENTE.DISPOSITIVO_USUARIO_ID_IX
ON  CLIENTE.DISPOSITIVO(USUARIO_ID)
TABLESPACE CLIENTE_IX_TBS;

-- 
-- TABLE: PLAYLIST 
--

CREATE INDEX CLIENTE.PLAYLIST_USUARIO_ID_IX
ON  CLIENTE.PLAYLIST(USUARIO_ID)
TABLESPACE CLIENTE_IX_TBS;

-- 
-- TABLE: PLAYLIST_USUARIO_COMPARTIDO 
--

CREATE INDEX CLIENTE.PUC_PLAYLIST_ID_IX
ON  CLIENTE.PLAYLIST_USUARIO_COMPARTIDO(PLAYLIST_ID)
TABLESPACE CLIENTE;

CREATE INDEX CLIENTE.PUC_USUARIO_ID_IX
ON  CLIENTE.PLAYLIST_USUARIO_COMPARTIDO(USUARIO_ID)
TABLESPACE CLIENTE;

-- 
-- TABLE: PLAYLIST_MULTIMEDIA 
--

CREATE INDEX    CLIENTE.PM_PLAYLIST_ID_IX
ON  CLIENTE.PLAYLIST_MULTIMEDIA(PLAYLIST_ID)
TABLESPACE CLIENTE_TBS;

CREATE INDEX CLIENTE.PM_CONTENIDO_MULTIMEDIA_ID_IX
ON  CLIENTE.PLAYLIST_MULTIMEDIA(CONTENIDO_MULTIMEDIA_ID)
TABLESPACE CLIENTE_TBS;

-- 
-- TABLE: REGISTRO_REPRODUCCION 
--

CREATE INDEX CLIENTE.RR_CONTENIDO_MULTIMEDIA_ID_IX
ON  CLIENTE.REGISTRO_REPRODUCCION(CONTENIDO_MULTIMEDIA_ID)
TABLESPACE CLIENTE_IX_TBS;

CREATE INDEX CLIENTE.RR_USUARIO_ID_IX
ON  CLIENTE.REGISTRO_REPRODUCCION(USUARIO_ID)
TABLESPACE CLIENTE_IX_TBS;

CREATE INDEX CLIENTE.RR_DISPOSITIVO_ID_IX
ON  CLIENTE.REGISTRO_REPRODUCCION(DISPOSITIVO_ID)
TABLESPACE CLIENTE_IX_TBS;

-- MODULO: MULTIMEDIA

-- 
-- TABLE: CALIFICACION 
--

CREATE INDEX MULTIMEDIA.CALIFICACION_USUARIO_ID_IX 
ON MULTIMEDIA.CALIFICACION(USUARIO_ID)  
TABLESPACE MULTIMEDIA_IX_TBS;

CREATE INDEX MULTIMEDIA.CALIFICACION_CONTENIDO_MULTIMEDIA_ID_IX 
ON   MULTIMEDIA.CALIFICACION(CONTENIDO_MULTIMEDIA_ID)
TABLESPACE MULTIMEDIA_IX_TBS;

-- 
-- TABLE: CONTENIDO_MULTIMEDIA 
--

CREATE UNIQUE INDEX MULTIMEDIA.CM_CLAVE_UK
ON  MULTIMEDIA.CONTENIDO_MULTIMEDIA(CLAVE)
TABLESPACE MULTIMEDIA_IX_TBS;

CREATE INDEX MULTIMEDIA.CM_GENERO_ID_IX
ON  MULTIMEDIA.CONTENIDO_MULTIMEDIA(GENERO_ID)
TABLESPACE MULTIMEDIA_IX_TBS;

-- 
-- TABLE: COMENTARIO 
--

CREATE INDEX MULTIMEDIA.C_COMENTARIO_ANTERIOR_ID_IX
ON  MULTIMEDIA.COMENTARIO(COMENTARIO_ANTERIOR_ID)
TABLESPACE MULTIMEDIA_IX_TBS;

CREATE INDEX MULTIMEDIA.C_CONTENIDO_MULTIMEDIA_ID_IX
ON  MULTIMEDIA.COMENTARIO(CONTENIDO_MULTIMEDIA_ID)
TABLESPACE MULTIMEDIA_IX_TBS;

CREATE INDEX MULTIMEDIA.C_USUARIO_ID_IX
ON  MULTIMEDIA.COMENTARIO(USUARIO_ID)
TABLESPACE MULTIMEDIA_IX_TBS;

-- 
-- TABLE: SECCION 
--

CREATE INDEX MULTIMEDIA.S_CONTENIDO_MULTIMEDIA_ID_IX
ON  MULTIMEDIA.SECCION(CONTENIDO_MULTIMEDIA_ID)
TABLESPACE MULTIMEDIA_IX_TBS;

-- 
-- TABLE: MULTIMEDIA_AUTOR 
--

CREATE INDEX MULTIMEDIA.MU_AUTOR_ID_IX
ON  MULTIMEDIA.MULTIMEDIA_AUTOR(AUTOR_ID)
TABLESPACE MULTIMEDIA_IX_TBS;

CREATE INDEX MULTIMEDIA.MU_CONTENIDO_MULTIMEDIA_ID_IX
ON  MULTIMEDIA.MULTIMEDIA_AUTOR(CONTENIDO_MULTIMEDIA_ID)
TABLESPACE MULTIMEDIA_IX_TBS;

-- 
-- TABLE: AUTOR 
--

CREATE UNIQUE INDEX MULTIMEDIA.A_EMAIL_UK
ON  MULTIMEDIA.AUTOR(EMAIL)
TABLESPACE MULTIMEDIA_IX_TBS;

-- 
-- TABLE: MUSICA 
--

CREATE INDEX MULTIMEDIA.M_FORMATO_AUDIO_ID_IX
ON  MULTIMEDIA.MUSICA(FORMATO_AUDIO_ID)
TABLESPACE MULTIMEDIA_IX_TBS;

-- 
-- TABLE: VIDEO 
--

CREATE INDEX MULTIMEDIA.V_TIPO_VIDEO_ID_IX
ON  MULTIMEDIA.VIDEO(TIPO_VIDEO_ID)
TABLESPACE MULTIMEDIA_IX_TBS;

CREATE INDEX MULTIMEDIA.V_CODIFICACION_VIDEO_ID_IX
ON  MULTIMEDIA.VIDEO(CODIFICACION_VIDEO_ID)
TABLESPACE MULTIMEDIA_IX_TBS;

CREATE INDEX MULTIMEDIA.V_TIPO_TRANSPORTE_ID_IX
ON  MULTIMEDIA.VIDEO(TIPO_TRANSPORTE_ID)
TABLESPACE MULTIMEDIA_IX_TBS;

CREATE INDEX MULTIMEDIA.V_PROTOCOLO_TRANSMICION_ID_IX
ON  MULTIMEDIA.VIDEO(PROTOCOLO_TRANSMICION_ID)
TABLESPACE MULTIMEDIA_IX_TBS;
